title:              Sameer Khanal Blog
email:              hello@khanalsameer.com.np
description:        Everything Web Design and Development
author:             Sameer Khanal
baseurl:            "/"
url:                "https://blog.khanalsameer.com.np"

# Social Profiles
twitter_username:   sameerkhanal209
github_username:    khanalsameer
facebook_username:  sameerkhanal209
linkedin_username:  sameerkhanal209

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
